import { useEffect, useState, useRef, FormEvent, useCallback, useId } from "react";
import { format, differenceInCalendarDays } from "date-fns";
import { CalendarRange, InfoIcon } from "lucide-react";
import {
  CalendarCheck2,
  CalendarClock,
  CalendarX2,
  Clock3,
  AlertCircle,
  RefreshCw,
  Users,
  Eye,
} from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

import api, { getErrorMessage } from "../lib/api";
import { useAuth } from "@/context/AuthContext";

import { PageHeader } from "@/components/PageHeader";
import { Spinner, FullSpinner } from "@/components/Spinner";
import { StatusBadge } from "@/components/StatusBadge";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

import { toast } from "@/hooks/use-toast";

interface Leave {
  id: string | number;
  employeeName?: string;
  leaveType: string;
  fromDate: string;
  toDate: string;
  dateType: string;
  halfSession?: string | null;
  days: number;
  reason: string;
  status?: string;
  // Populated only while status === "REAPPROVAL_PENDING" — the employee's
  // proposed changes to an already-approved leave. The fields above still
  // hold the original, currently-approved values until an owner accepts it.
  pendingFromDate?: string | null;
  pendingToDate?: string | null;
  pendingDateType?: string | null;
  pendingHalfSession?: string | null;
  pendingLeaveType?: string | null;
  pendingReason?: string | null;
  pendingDays?: number | null;
  // Present and true only on leave records auto-generated by the Permission
  // portal once an employee's monthly permission hours cross the free
  // allowance (see PermissionSurplusService on the backend). surplusMonth
  // is the "yyyy-MM" it covers; surplusHoursSnapshot is the hour total that
  // triggered it, shown to explain where the half/full day came from.
  surplusPermission?: boolean | null;
  surplusMonth?: string | null;
  surplusHoursSnapshot?: number | null;
}

// One row of the owner's "All Employees" overview — every employee's
// leave days used/remaining for the current year, in one page.
interface EmployeeLeaveSummary {
  employeeName: string;
  daysUsed: number;
  daysRemaining: number;
  leaveLimit: number;
  isOverLimit: boolean;
}

/* ─── Constants ─────────────────────────────────────────── */

// Default/fallback leave limit shown before the real, per-employee value
// (derived from their date of joining) has loaded from
// GET /leaves/leave-limit. See LeavePolicy on the backend:
//   • 3+ years of service → 24 days/year
//   • under 1 year       → 18 days/year
const DEFAULT_LEAVE_LIMIT = 18;
const MIN_DATE_OFFSET = 1;

const DATE_TYPE_LABELS: Record<string, string> = {
  SINGLE: "Single day",
  RANGE: "Date range",
  HALF_DAY: "Half day",
};

const formatDateType = (dateType?: string, halfSession?: string | null) => {
  if (!dateType) return "";
  const base = DATE_TYPE_LABELS[dateType] ?? dateType.toLowerCase().replace(/_/g, " ");
  if (dateType === "HALF_DAY" && halfSession) {
    const sessionLabel = halfSession === "SECOND_HALF" ? "2nd half" : "1st half";
    return `${base} · ${sessionLabel}`;
  }
  return base;
};

// Badge for leave records auto-generated by the Permission portal once an
// employee's cumulative APPROVED permission hours for the month cross the
// free allowance (see PermissionSurplusService on the backend):
//   • days >= 1   → "Full-Day Permission"  (>= 9h approved that month)
//   • days < 1    → "Half-Day Permission"  (>= 4h and < 9h approved that month)
// This label is the leave entry's actual name/classification, not just a
// decorative tag, so it must read exactly "Half-Day Permission" /
// "Full-Day Permission" per the business rule.
const SurplusBadge = ({ leave }: { leave: Leave }) => {
  if (!leave.surplusPermission) return null;
  const isFullDay = (leave.days ?? 0) >= 1;
  const label = isFullDay ? "Full-Day Permission" : "Half-Day Permission";
  const title = leave.surplusMonth
    ? `Auto-generated from ${leave.surplusHoursSnapshot ?? "?"}h of approved permission used in ${leave.surplusMonth}`
    : undefined;
  return (
    <span
      title={title}
      className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700 dark:border-amber-800 dark:bg-amber-950/50 dark:text-amber-400"
    >
      <span aria-hidden="true">⚖️</span> {label}
    </span>
  );
};

// A leave can only be changed ("reapproval") while it is APPROVED and its
// start date hasn't arrived yet — mirrors the same check the backend enforces.
const canRequestChange = (l: Leave) => {
  if (l.status?.toUpperCase() !== "APPROVED") return false;
  if (!l.fromDate) return false;
  const from = new Date(l.fromDate);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  from.setHours(0, 0, 0, 0);
  return from.getTime() > today.getTime();
};

/* ─── Helpers ───────────────────────────────────────────── */

const calcDays = (from: string, to: string) => {
  try {
    const days = differenceInCalendarDays(new Date(to), new Date(from)) + 1;
    return Math.max(1, days);
  } catch {
    return 1;
  }
};

const formatDays = (n: number) => {
  const rounded = Math.round(n * 10) / 10; // keep 1 decimal, avoid float noise
  return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(1);
};

const fmt = (d: string) => {
  try {
    return format(new Date(d), "MMM d, yyyy");
  } catch {
    return d ?? "—";
  }
};

// Compact duration badge: "Xd".
const formatDurationBadge = (days?: number | null) => {
  return `${formatDays(days || 0)}d`;
};

const getToday = () => format(new Date(), "yyyy-MM-dd");
const getMinDate = () => {
  const date = new Date();
  date.setDate(date.getDate() + MIN_DATE_OFFSET);
  return format(date, "yyyy-MM-dd");
};

/* ─── Design tokens (colors, badges) ───────────────────────
   Centralized here so light/dark parity is easy to audit and
   every consumer (employee + owner views) stays visually consistent. */

const LEAVE_TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  SICK: {
    bg: "bg-red-50 dark:bg-red-950/40",
    text: "text-red-700 dark:text-red-400",
    border: "border-red-200 dark:border-red-900",
  },
  CASUAL: {
    bg: "bg-blue-50 dark:bg-blue-950/40",
    text: "text-blue-700 dark:text-blue-400",
    border: "border-blue-200 dark:border-blue-900",
  },
  ANNUAL: {
    bg: "bg-green-50 dark:bg-green-950/40",
    text: "text-green-700 dark:text-green-400",
    border: "border-green-200 dark:border-green-900",
  },
  EARNED: {
    bg: "bg-green-50 dark:bg-green-950/40",
    text: "text-green-700 dark:text-green-400",
    border: "border-green-200 dark:border-green-900",
  },
  MATERNITY: {
    bg: "bg-pink-50 dark:bg-pink-950/40",
    text: "text-pink-700 dark:text-pink-400",
    border: "border-pink-200 dark:border-pink-900",
  },
  PATERNITY: {
    bg: "bg-indigo-50 dark:bg-indigo-950/40",
    text: "text-indigo-700 dark:text-indigo-400",
    border: "border-indigo-200 dark:border-indigo-900",
  },
  EMERGENCY: {
    bg: "bg-orange-50 dark:bg-orange-950/40",
    text: "text-orange-700 dark:text-orange-400",
    border: "border-orange-200 dark:border-orange-900",
  },
  UNPAID: {
    bg: "bg-slate-100 dark:bg-slate-800/60",
    text: "text-slate-600 dark:text-slate-300",
    border: "border-slate-200 dark:border-slate-700",
  },
};

const getLeaveTypeColors = (leaveType: string) =>
  LEAVE_TYPE_COLORS[leaveType] ?? {
    bg: "bg-muted",
    text: "text-foreground",
    border: "border-border",
  };

/* ─── Enhanced Animations ────────────────────────────────── */

const animationStyles = `
  @keyframes fadeSlideDown {
    0%   { opacity: 0; transform: translateY(-16px) scale(0.96); }
    100% { opacity: 1; transform: translateY(0) scale(1); }
  }
  @keyframes fadeInUp {
    from { opacity: 0; transform: translateY(-8px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  @keyframes slideInRight {
    from { opacity: 0; transform: translateX(28px); }
    to   { opacity: 1; transform: translateX(0); }
  }
  @keyframes leaveWarnPulse {
    0%, 100% { box-shadow: 0 0 0 0 rgba(239,68,68,0.35); }
    50%       { box-shadow: 0 0 0 8px rgba(239,68,68,0); }
  }
  @keyframes leaveShake {
    0%,100% { transform: translateX(0); }
    20%     { transform: translateX(-4px); }
    40%     { transform: translateX(4px); }
    60%     { transform: translateX(-3px); }
    80%     { transform: translateX(3px); }
  }
  @keyframes empWarnPulse {
    0%, 100% { box-shadow: 0 0 0 0 rgba(239,68,68,0.4); }
    50%      { box-shadow: 0 0 0 10px rgba(239,68,68,0); }
  }
  @keyframes empGoodPulse {
    0%, 100% { box-shadow: 0 0 0 0 rgba(34,197,94,0.3); }
    50%      { box-shadow: 0 0 0 10px rgba(34,197,94,0); }
  }
  @keyframes empShake {
    0%,100% { transform: translateX(0); }
    20%     { transform: translateX(-4px); }
    40%     { transform: translateX(4px); }
    60%     { transform: translateX(-3px); }
    80%     { transform: translateX(3px); }
  }
  @keyframes empSlideIn {
    from { opacity: 0; transform: translateY(-6px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  @keyframes successBounce {
    0% { transform: scale(0.3); opacity: 0; }
    50% { transform: scale(1.05); }
    70% { transform: scale(0.9); }
    100% { transform: scale(1); opacity: 1; }
  }
  @keyframes floatUp {
    from { opacity: 0; transform: translateY(10px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  @keyframes subtlePulse {
    0%,100% { transform: scale(1); }
    50%     { transform: scale(1.06); }
  }
  .animate-fade-slide-down {
    animation: fadeSlideDown 0.25s cubic-bezier(0.34,1.2,0.64,1) forwards;
  }
  .animate-fade-in-up {
    animation: fadeInUp 0.3s ease-out;
  }
  .animate-slide-right {
    animation: slideInRight 0.4s ease-out;
  }
  .animate-success-bounce {
    animation: successBounce 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
  }
  .card-hover {
    transition: box-shadow 0.25s ease, transform 0.25s ease;
  }
  .card-hover:hover {
    box-shadow: 0 12px 24px -8px rgba(0,0,0,.08), 0 4px 8px -4px rgba(0,0,0,.04);
  }
  .btn-hover-scale {
    transition: transform 0.15s cubic-bezier(0.4,0,0.2,1);
  }
  .btn-hover-scale:hover {
    transform: scale(1.03);
  }
  .btn-hover-scale:active {
    transform: scale(0.97);
  }
  .leave-card {
    transition: box-shadow 0.2s ease, border-color 0.2s ease;
  }
  .leave-card:hover {
    box-shadow: 0 6px 16px -6px rgba(0,0,0,.10);
  }
  .table-row-animate {
    animation: floatUp 0.35s ease-out forwards;
    opacity: 0;
  }
  .tab-transition {
    transition: background-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease;
  }
  .custom-scrollbar::-webkit-scrollbar {
    width: 6px;
  }
  .custom-scrollbar::-webkit-scrollbar-track {
    background: transparent;
  }
  .custom-scrollbar::-webkit-scrollbar-thumb {
    background: hsl(var(--border));
    border-radius: 3px;
  }
  .custom-scrollbar::-webkit-scrollbar-thumb:hover {
    background: hsl(var(--muted-foreground) / 0.4);
  }
  /* Respect reduced-motion preferences across the whole portal */
  @media (prefers-reduced-motion: reduce) {
    .animate-fade-slide-down,
    .animate-fade-in-up,
    .animate-slide-right,
    .animate-success-bounce,
    .table-row-animate {
      animation: none !important;
      opacity: 1 !important;
      transform: none !important;
    }
    .card-hover,
    .btn-hover-scale,
    .leave-card,
    .tab-transition {
      transition: none !important;
    }
  }
`;

if (typeof document !== "undefined") {
  const styleId = "leave-portal-animations";
  if (!document.getElementById(styleId)) {
    const s = document.createElement("style");
    s.id = styleId;
    s.textContent = animationStyles;
    document.head.appendChild(s);
  }
}

/* Shared focus-visible ring used on custom (non-shadcn) interactive elements
   so keyboard users always get a clear indicator. */
const FOCUS_RING =
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background";

/* =========================================================
   LEAVE OPTION COMPONENT
========================================================= */

const LeaveOption = ({
  title,
  description,
}: {
  title: string;
  description: string;
}) => (
  <div className="flex w-full items-center justify-between gap-2">
    <span>{title}</span>
    <TooltipProvider delayDuration={100}>
      <Tooltip>
        <TooltipTrigger asChild>
          <button
            type="button"
            className={`inline-flex items-center rounded-full p-0.5 text-muted-foreground transition-colors hover:bg-muted hover:text-primary ${FOCUS_RING}`}
            onClick={(e) => e.stopPropagation()}
            aria-label={`More info about ${title}`}
          >
            <InfoIcon className="h-4 w-4" aria-hidden="true" />
          </button>
        </TooltipTrigger>
        <TooltipContent side="right" align="center" sideOffset={10} className="z-[9999] max-w-xs">
          <p className="font-medium">{title}</p>
          <p className="whitespace-pre-line text-xs text-muted-foreground">{description}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  </div>
);

/* =========================================================
   TAB BUTTON — shared, accessible tab control
   Used by both the employee history filter and the owner
   pending/employee toggle so keyboard + ARIA semantics and
   visual styling stay identical everywhere in the portal.
========================================================= */

const TabButton = ({
  active,
  onClick,
  icon: Icon,
  label,
  count,
  controls,
}: {
  active: boolean;
  onClick: () => void;
  icon?: React.ComponentType<{ className?: string }>;
  label: string;
  count?: number;
  controls?: string;
}) => (
  <button
    type="button"
    role="tab"
    aria-selected={active}
    aria-controls={controls}
    tabIndex={active ? 0 : -1}
    onClick={onClick}
    className={`tab-transition flex flex-1 min-w-[76px] items-center justify-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium ${FOCUS_RING} ${
      active
        ? "bg-background text-foreground shadow-sm"
        : "text-muted-foreground hover:text-foreground"
    }`}
  >
    {Icon && <Icon className="h-3.5 w-3.5" aria-hidden="true" />}
    <span>{label}</span>
    {typeof count === "number" && count > 0 && (
      <span
        className={`ml-0.5 min-w-[1.1rem] rounded-full px-1.5 py-0.5 text-center text-[10px] font-semibold leading-none ${
          active ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
        }`}
      >
        {count}
      </span>
    )}
  </button>
);

/* =========================================================
   LEAVE TAKEN SUMMARY
========================================================= */

const LeaveTakenSummary = ({ leaves, leaveLimit }: { leaves: Leave[]; leaveLimit: number }) => {
  const currentYear = new Date().getFullYear();

  const takenDays = leaves
    .filter(
      (l) =>
        l.status?.toUpperCase() === "APPROVED" &&
        new Date(l.fromDate).getFullYear() === currentYear
    )
    .reduce((sum, l) => sum + (l.days || 0), 0);

  const isOverLimit = takenDays > leaveLimit;
  const remainingDays = leaveLimit - takenDays;

  const ringColor = isOverLimit ? "#ef4444" : "#22c55e";
  const pulseColor = isOverLimit ? "#ef4444" : "#22c55e";
  const numberColor = isOverLimit ? "#ef4444" : "#22c55e";

  const [displayed, setDisplayed] = useState(0);
  const [started, setStarted] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const animationFrameRef = useRef<number>();

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setStarted(true);
          observer.disconnect();
        }
      },
      { threshold: 0.4 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (!started || takenDays === 0) {
      setDisplayed(takenDays);
      return;
    }
    setDisplayed(0);
    const duration = 900;
    const start = performance.now();
    const tick = (now: number) => {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setDisplayed(Math.round(eased * takenDays * 10) / 10);
      if (progress < 1) {
        animationFrameRef.current = requestAnimationFrame(tick);
      }
    };
    animationFrameRef.current = requestAnimationFrame(tick);
    return () => {
      if (animationFrameRef.current) cancelAnimationFrame(animationFrameRef.current);
    };
  }, [started, takenDays]);

  const fillRatio = Math.min(takenDays / leaveLimit, 1);
  const circumference = 2 * Math.PI * 44;

  return (
    <div ref={ref} className="flex flex-col items-center justify-center gap-6 py-10">
      {isOverLimit && (
        <div
          role="alert"
          className="w-full max-w-sm animate-fade-slide-down rounded-lg border border-red-300 bg-red-50 px-4 py-3 text-center dark:border-red-900/60 dark:bg-red-950/30"
          style={{ animation: "leaveWarnPulse 1.8s ease-in-out infinite" }}
        >
          <p
            className="text-sm font-bold text-red-600 dark:text-red-400"
            style={{ animation: "leaveShake 0.5s ease-in-out 0.3s 1" }}
          >
            <span aria-hidden="true">⚠</span> Leave limit exceeded
          </p>
          <p className="mt-0.5 text-xs text-red-500 dark:text-red-400/80">
            You've taken {takenDays} days — {Math.abs(remainingDays)} day
            {Math.abs(remainingDays) !== 1 ? "s" : ""} over the {leaveLimit}-day limit.
          </p>
        </div>
      )}

      <div className="relative flex items-center justify-center">
        <span
          className="absolute inline-flex h-40 w-40 animate-ping rounded-full opacity-20"
          style={{
            background: `radial-gradient(circle, ${pulseColor} 0%, transparent 70%)`,
            animationDuration: "2.4s",
          }}
          aria-hidden="true"
        />
        <svg className="absolute h-44 w-44 -rotate-90" viewBox="0 0 100 100" aria-hidden="true">
          <circle cx="50" cy="50" r="44" fill="none" stroke="hsl(var(--border))" strokeWidth="5" />
          <circle
            cx="50"
            cy="50"
            r="44"
            fill="none"
            stroke={ringColor}
            strokeWidth="5"
            strokeLinecap="round"
            strokeDasharray={`${circumference}`}
            strokeDashoffset={started ? `${circumference * (1 - fillRatio)}` : `${circumference}`}
            style={{
              transition: "stroke-dashoffset 0.9s cubic-bezier(0.16,1,0.3,1), stroke 0.4s ease",
            }}
          />
        </svg>
        <div
          className="relative flex h-32 w-32 flex-col items-center justify-center rounded-full bg-background shadow-inner"
          role="status"
          aria-live="polite"
        >
          <span
            className="text-5xl font-bold leading-none tabular-nums"
            style={{
              color: numberColor,
              opacity: started ? 1 : 0,
              transform: started ? "scale(1)" : "scale(0.7)",
              transition:
                "opacity 0.4s ease, transform 0.4s cubic-bezier(0.34,1.56,0.64,1), color 0.4s ease",
            }}
          >
            {formatDays(displayed)}
          </span>
          <span className="mt-1 text-[11px] font-medium uppercase tracking-widest text-muted-foreground">
            {takenDays === 1 ? "day" : "days"}
          </span>
        </div>
      </div>

      <div className="space-y-1 text-center">
        <p className="text-base font-semibold text-foreground">Leave taken in {currentYear}</p>
        {takenDays === 0 ? (
          <p className="text-sm text-muted-foreground">No approved leaves taken this year.</p>
        ) : isOverLimit ? (
          <p className="text-sm font-semibold text-red-500 dark:text-red-400">
            {takenDays} / {leaveLimit} days — exceeded by {Math.abs(remainingDays)} day
            {Math.abs(remainingDays) !== 1 ? "s" : ""}
          </p>
        ) : (
          <p className="text-sm font-medium text-green-600 dark:text-green-400">
            {takenDays} / {leaveLimit} days taken &mdash;{" "}
            <span className="font-semibold">
              {remainingDays} day{remainingDays !== 1 ? "s" : ""} remaining
            </span>
          </p>
        )}
      </div>
    </div>
  );
};

/* =========================================================
   EMPTY STATE — shared
========================================================= */

const EmptyState = ({
  icon: Icon = CalendarX2,
  message,
}: {
  icon?: React.ComponentType<{ className?: string }>;
  message: string;
}) => (
  <div className="flex flex-col items-center gap-2 py-10 text-center text-muted-foreground animate-fade-in-up">
    <Icon className="h-8 w-8 opacity-30" aria-hidden="true" />
    <p className="text-sm">{message}</p>
  </div>
);

/* =========================================================
   ERROR STATE — shared
========================================================= */

const ErrorState = ({ message, onRetry }: { message: string; onRetry: () => void }) => (
  <div
    role="alert"
    className="animate-fade-in-up rounded-md border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"
  >
    <div className="flex items-center gap-2">
      <AlertCircle className="h-4 w-4 flex-shrink-0" aria-hidden="true" />
      <span>{message}</span>
    </div>
    <button
      type="button"
      onClick={onRetry}
      className={`mt-2 flex items-center gap-1 rounded text-xs text-destructive hover:underline ${FOCUS_RING}`}
    >
      <RefreshCw className="h-3 w-3" aria-hidden="true" />
      Try again
    </button>
  </div>
);

/* =========================================================
   LEAVE CARD — shared card used across employee + owner views
   Consolidates what used to be three near-identical card
   layouts (employee history, owner pending queue, owner's
   view of a single employee's history) into one component so
   spacing, color, and a11y stay in sync everywhere.
========================================================= */

interface LeaveCardProps {
  leave: Leave;
  index?: number;
  showEmployee?: boolean;
  onRequestChange?: (l: Leave) => void;
  onCancelReapproval?: (l: Leave) => void;
  cancelingId?: string | number | null;
  onApprove?: (l: Leave) => void;
  onReject?: (l: Leave) => void;
  actingId?: string | number | null;
}

const LeaveCard = ({
  leave: l,
  index = 0,
  showEmployee = false,
  onRequestChange,
  onCancelReapproval,
  cancelingId,
  onApprove,
  onReject,
  actingId,
}: LeaveCardProps) => {
  const colors = getLeaveTypeColors(l.leaveType);
  const isSingleDay = l.fromDate === l.toDate;
  const isReapproval = l.status?.toUpperCase() === "REAPPROVAL_PENDING";
  const isBusy = actingId === l.id;
  const isCanceling = cancelingId === l.id;

  return (
    <div
      className="leave-card table-row-animate rounded-xl border border-border/60 bg-card p-4 shadow-sm"
      style={{ animationDelay: `${Math.min(index, 12) * 0.04}s` }}
    >
      {/* Top row: (optional avatar+name) + type badge + days + status */}
      <div className="mb-2 flex flex-wrap items-center gap-2">
        {showEmployee && (
          <>
            <div
              className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-indigo-100 text-sm font-bold text-indigo-600 dark:bg-indigo-950/50 dark:text-indigo-400"
              aria-hidden="true"
            >
              {(l.employeeName || "?")[0]?.toUpperCase()}
            </div>
            <span className="text-sm font-semibold text-foreground">{l.employeeName || "—"}</span>
          </>
        )}
        <span
          className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold ${colors.bg} ${colors.text} ${colors.border}`}
        >
          {l.leaveType}
        </span>
        <SurplusBadge leave={l} />
        <div className="ml-auto flex items-center gap-2">
          <span className="inline-flex items-center gap-1 rounded-lg bg-muted px-2.5 py-1 text-xs font-bold text-foreground">
            <Clock3 className="h-3.5 w-3.5 text-muted-foreground" aria-hidden="true" />
            {formatDurationBadge(l.days ?? calcDays(l.fromDate, l.toDate))}
          </span>
          <StatusBadge status={l.status} />
        </div>
      </div>

      {/* Dates + reason (struck through when a reapproval is pending) */}
      <div className="space-y-1">
        <div className="flex flex-wrap items-center gap-2 text-sm font-semibold text-foreground">
          <CalendarCheck2 className="h-3.5 w-3.5 flex-shrink-0 text-muted-foreground" aria-hidden="true" />
          <span className={isReapproval ? "text-muted-foreground line-through opacity-70" : ""}>
            {isSingleDay ? (
              fmt(l.fromDate)
            ) : (
              <>
                {fmt(l.fromDate)} <span className="font-normal text-muted-foreground">→</span> {fmt(l.toDate)}
              </>
            )}
          </span>
        </div>
        {l.dateType && !isReapproval && (
          <p className="pl-5 text-xs text-muted-foreground">{formatDateType(l.dateType, l.halfSession)}</p>
        )}
        {l.reason && !isReapproval && (
          <p className="pl-5 text-xs leading-relaxed text-muted-foreground line-clamp-2" title={l.reason}>
            {l.reason}
          </p>
        )}
      </div>

      {/* Reapproval: proposed changes */}
      {isReapproval && (
        <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 dark:border-amber-900/50 dark:bg-amber-950/30">
          <p className="mb-1.5 text-xs font-semibold text-amber-700 dark:text-amber-400">
            {showEmployee ? "Requested change" : "Reapproval requested — awaiting owner's decision"}
          </p>
          <div className="flex flex-wrap items-center gap-1.5 text-xs font-semibold text-amber-800 dark:text-amber-300">
            <CalendarCheck2 className="h-3 w-3 flex-shrink-0" aria-hidden="true" />
            {l.pendingFromDate === l.pendingToDate ? (
              fmt(l.pendingFromDate || "")
            ) : (
              <>
                {fmt(l.pendingFromDate || "")} <span aria-hidden="true">→</span> {fmt(l.pendingToDate || "")}
              </>
            )}
            {l.pendingDateType && (
              <span className="font-normal text-amber-700 dark:text-amber-400/90">
                · {formatDateType(l.pendingDateType, l.pendingHalfSession)}
              </span>
            )}
          </div>
          {l.pendingReason && (
            <p className="mt-1 text-xs text-amber-700 line-clamp-2 dark:text-amber-400/90" title={l.pendingReason}>
              {showEmployee ? l.pendingReason : `New reason: ${l.pendingReason}`}
            </p>
          )}
          {onCancelReapproval && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => onCancelReapproval(l)}
              disabled={isCanceling}
              className="btn-hover-scale mt-2 h-7 text-xs"
            >
              {isCanceling ? <Spinner className="mr-1 h-3 w-3" /> : null}
              Cancel request
            </Button>
          )}
        </div>
      )}

      {/* Employee: request a change to an approved, not-yet-started leave */}
      {!isReapproval && onRequestChange && canRequestChange(l) && (
        <div className="mt-3">
          <Button size="sm" variant="outline" onClick={() => onRequestChange(l)} className="btn-hover-scale h-7 text-xs">
            Request change
          </Button>
        </div>
      )}

      {/* Owner: approve / reject actions */}
      {(onApprove || onReject) && (l.status?.toUpperCase() === "PENDING" || isReapproval) && (
        <div className="mt-3 flex flex-wrap items-center gap-2">
          {onApprove && (
            <Button
              size="sm"
              onClick={() => onApprove(l)}
              disabled={isBusy}
              className="btn-hover-scale h-7 flex-1 text-xs sm:flex-none"
            >
              {isBusy ? <Spinner className="mr-1 h-3 w-3" /> : null}
              {isReapproval ? "Approve change" : "Approve"}
            </Button>
          )}
          {onReject && (
            <Button
              size="sm"
              variant="destructive"
              onClick={() => onReject(l)}
              disabled={isBusy}
              className="btn-hover-scale h-7 flex-1 text-xs sm:flex-none"
            >
              {isBusy ? <Spinner className="mr-1 h-3 w-3" /> : null}
              {isReapproval ? "Reject change" : "Reject"}
            </Button>
          )}
        </div>
      )}
    </div>
  );
};

/* =========================================================
   APPLIED LEAVES LIST
========================================================= */

const AppliedLeavesTable = ({
  leaves,
  onRequestChange,
  onCancelReapproval,
  cancelingId,
}: {
  leaves: Leave[];
  onRequestChange?: (l: Leave) => void;
  onCancelReapproval?: (l: Leave) => void;
  cancelingId?: string | number | null;
}) => {
  if (leaves.length === 0) {
    return <EmptyState message="No leave requests yet." />;
  }

  const sortedLeaves = [...leaves].sort((a, b) => {
    try {
      return new Date(b.fromDate).getTime() - new Date(a.fromDate).getTime();
    } catch {
      return 0;
    }
  });

  return (
    <div className="space-y-3">
      {sortedLeaves.map((l, index) => (
        <LeaveCard
          key={l.id}
          leave={l}
          index={index}
          onRequestChange={onRequestChange}
          onCancelReapproval={onCancelReapproval}
          cancelingId={cancelingId}
        />
      ))}
    </div>
  );
};

/* =========================================================
   ALL-EMPLOYEES SUMMARY TABLE
   Shows every employee's leave days used/remaining for the
   current year on a single page, so an owner doesn't have to select
   employees one at a time just to see where everyone stands.
========================================================= */

const EmployeeSummaryTable = ({
  summaries,
  onView,
}: {
  summaries: EmployeeLeaveSummary[];
  onView: (employeeName: string) => void;
}) => {
  return (
    <div className="custom-scrollbar overflow-x-auto rounded-lg border border-border">
      <table className="w-full min-w-[640px] text-sm">
        <caption className="sr-only">Leave days used and remaining for every employee this year</caption>
        <thead>
          <tr className="border-b border-border bg-muted/40 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            <th scope="col" className="px-4 py-2.5">Employee</th>
            <th scope="col" className="px-4 py-2.5">Days used</th>
            <th scope="col" className="px-4 py-2.5">Days remaining</th>
            <th scope="col" className="px-4 py-2.5">Status</th>
            <th scope="col" className="px-4 py-2.5">
              <span className="sr-only">Actions</span>
            </th>
          </tr>
        </thead>
        <tbody>
          {summaries.map(({ employeeName, daysUsed, daysRemaining, leaveLimit, isOverLimit }) => {
            const pct = Math.min((daysUsed / (leaveLimit || 1)) * 100, 100);
            return (
              <tr key={employeeName} className="border-b border-border/60 last:border-0 hover:bg-muted/30">
                <td className="px-4 py-3">
                  <div className="flex min-w-0 items-center gap-2">
                    <div
                      className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-indigo-100 text-[10px] font-bold text-indigo-600 dark:bg-indigo-950/50 dark:text-indigo-400"
                      aria-hidden="true"
                    >
                      {employeeName[0]?.toUpperCase() ?? "?"}
                    </div>
                    <span className="truncate font-medium text-foreground">{employeeName}</span>
                  </div>
                </td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    <span className="font-semibold text-foreground">
                      {formatDays(daysUsed)} / {leaveLimit}d
                    </span>
                    <div className="hidden h-1.5 w-16 overflow-hidden rounded-full bg-muted sm:block">
                      <div className={`h-full rounded-full ${isOverLimit ? "bg-red-500" : "bg-green-500"}`} style={{ width: `${pct}%` }} />
                    </div>
                  </div>
                </td>
                <td className="px-4 py-3">
                  <span
                    className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold ${
                      isOverLimit
                        ? "bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-400"
                        : daysRemaining <= 5
                        ? "bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-400"
                        : "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400"
                    }`}
                  >
                    {isOverLimit ? `${Math.abs(daysRemaining)}d over` : `${formatDays(daysRemaining)}d left`}
                  </span>
                </td>
                <td className="px-4 py-3">
                  {isOverLimit ? (
                    <span className="inline-flex items-center rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-700 dark:bg-red-950/50 dark:text-red-400">
                      ⚠ Exceeded
                    </span>
                  ) : daysRemaining <= 5 ? (
                    <span className="inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-semibold text-amber-700 dark:bg-amber-950/50 dark:text-amber-400">
                      Low balance
                    </span>
                  ) : (
                    <span className="inline-flex items-center rounded-full bg-green-100 px-2 py-0.5 text-xs font-semibold text-green-700 dark:bg-green-950/50 dark:text-green-400">
                      ✓ On track
                    </span>
                  )}
                </td>
                <td className="px-4 py-3 text-right">
                  <Button size="sm" variant="outline" className="btn-hover-scale h-7 text-xs" onClick={() => onView(employeeName)}>
                    <Eye className="mr-1 h-3 w-3" aria-hidden="true" />
                    View
                  </Button>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
};

/* =========================================================
   EMPLOYEE VIEW
========================================================= */

const EmployeeView = () => {
  const { name } = useAuth();
  const historyPanelId = useId();

  const [leaveType, setLeaveType] = useState("SICK");
  const [dateMode, setDateMode] = useState<"single" | "range" | "half">("single");
  const [halfSession, setHalfSession] = useState<"FIRST_HALF" | "SECOND_HALF">("FIRST_HALF");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [reason, setReason] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [leaves, setLeaves] = useState<Leave[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [historyTab, setHistoryTab] = useState<"pending" | "all" | "approved" | "rejected">("pending");
  // "yyyy-MM", defaults to the current month — mirrors the owner's month
  // filter so employees can browse their own history by month too.
  const [historyMonth, setHistoryMonth] = useState<string>(() => format(new Date(), "yyyy-MM"));
  const [leaveLimit, setLeaveLimit] = useState<number>(DEFAULT_LEAVE_LIMIT);

  // ── Reapproval state ──────────────────────────────────────────
  const [reapprovalTarget, setReapprovalTarget] = useState<Leave | null>(null);
  const [reDateMode, setReDateMode] = useState<"single" | "range" | "half">("single");
  const [reHalfSession, setReHalfSession] = useState<"FIRST_HALF" | "SECOND_HALF">("FIRST_HALF");
  const [reFromDate, setReFromDate] = useState("");
  const [reToDate, setReToDate] = useState("");
  const [reReason, setReReason] = useState("");
  const [reSubmitting, setReSubmitting] = useState(false);
  const [cancelingId, setCancelingId] = useState<string | number | null>(null);

  const initialLoadDoneRef = useRef(false);
  const loadingLockRef = useRef(false);
  const modalCloseButtonRef = useRef<HTMLButtonElement>(null);

  // ── Load leaves ──────────────────────────────────────────────
  const load = useCallback(async () => {
    if (!name) return;
    if (loadingLockRef.current) return;
    loadingLockRef.current = true;
    setLoading(true);
    setError(null);
    try {
      const { data } = await api.get<Leave[]>("/leaves/employee", {
        params: { employeeName: name },
      });
      setLeaves(data);
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setLoading(false);
      loadingLockRef.current = false;
    }
  }, [name]);

  useEffect(() => {
    if (!initialLoadDoneRef.current) {
      initialLoadDoneRef.current = true;
      load();
    }
  }, [load]);

  // ── Leave limit ─────────────────────────────────────────────
  const fetchLeaveLimit = useCallback(async () => {
    if (!name) return;
    try {
      const { data } = await api.get<{ leaveLimit: number }>("/leaves/leave-limit", {
        params: { employeeName: name },
        headers: { "Cache-Control": "no-cache" },
      });
      setLeaveLimit(data.leaveLimit);
    } catch {
      // non-fatal
    }
  }, [name]);

  useEffect(() => {
    fetchLeaveLimit();
  }, [fetchLeaveLimit]);

  useEffect(() => {
    const onFocus = () => fetchLeaveLimit();
    const onVisibility = () => {
      if (document.visibilityState === "visible") fetchLeaveLimit();
    };
    window.addEventListener("focus", onFocus);
    document.addEventListener("visibilitychange", onVisibility);
    return () => {
      window.removeEventListener("focus", onFocus);
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, [fetchLeaveLimit]);

  // ── Form helpers ─────────────────────────────────────────────
  const resetForm = () => {
    setFromDate("");
    setToDate("");
    setReason("");
    setLeaveType("SICK");
    setDateMode("single");
    setHalfSession("FIRST_HALF");
  };

  const validateForm = (): string | null => {
    if (!name) return "User name is required. Please log in again.";
    if (!fromDate) return "Please select a date.";
    if (dateMode === "range" && !toDate) return "Please select an end date.";
    if (dateMode === "range") {
      const fromDateObj = new Date(fromDate);
      const toDateObj = new Date(toDate);
      if (toDateObj < fromDateObj) return "End date cannot be before start date.";
      const days = calcDays(fromDate, toDate);
      if (days > 30) return "Leave duration cannot exceed 30 days. Please contact your manager.";
    }
    if (!reason.trim()) return "Please provide a reason for your leave.";
    if (reason.trim().length < 10) return "Reason must be at least 10 characters.";
    return null;
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    const validationError = validateForm();
    if (validationError) {
      toast({ title: "Validation error", description: validationError, variant: "destructive" });
      return;
    }
    setSubmitting(true);
    const effectiveToDate = dateMode === "range" ? toDate : fromDate;
    const dateType = dateMode === "half" ? "HALF_DAY" : dateMode.toUpperCase();
    let days: number;
    if (dateMode === "range") days = calcDays(fromDate, toDate);
    else if (dateMode === "half") days = 0.5;
    else days = 1;
    try {
      await api.post<Leave>("/leaves/request", {
        employeeName: name,
        leaveType,
        fromDate,
        toDate: effectiveToDate,
        dateType,
        halfSession: dateMode === "half" ? halfSession : null,
        days,
        reason: reason.trim(),
      });
      toast({
        title: "Leave request submitted",
        description: "Your leave request has been submitted successfully.",
        className: "border-green-500 bg-green-500 text-white animate-success-bounce",
      });
      resetForm();
      await load();
    } catch (err) {
      toast({
        title: "Couldn't submit request",
        description: getErrorMessage(err) || "An unexpected error occurred.",
        variant: "destructive",
      });
    } finally {
      setSubmitting(false);
    }
  };

  // ── Reapproval handlers ─────────────────────────────────────
  const openReapproval = (l: Leave) => {
    setReapprovalTarget(l);
    const mode = l.dateType === "HALF_DAY" ? "half" : l.dateType === "RANGE" ? "range" : "single";
    setReDateMode(mode as "single" | "range" | "half");
    setReHalfSession((l.halfSession as "FIRST_HALF" | "SECOND_HALF") || "FIRST_HALF");
    setReFromDate(l.fromDate ? l.fromDate.slice(0, 10) : "");
    setReToDate(l.toDate ? l.toDate.slice(0, 10) : "");
    setReReason(l.reason || "");
  };

  const closeReapproval = () => {
    if (reSubmitting) return;
    setReapprovalTarget(null);
  };

  // Close the reapproval modal on Escape and move focus to the close button
  // when it opens, for a properly accessible dialog experience.
  useEffect(() => {
    if (!reapprovalTarget) return;
    modalCloseButtonRef.current?.focus();
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") closeReapproval();
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reapprovalTarget]);

  const validateReapproval = (): string | null => {
    if (!reFromDate) return "Please select a date.";
    if (reDateMode === "range" && !reToDate) return "Please select an end date.";
    if (reDateMode === "range") {
      const days = calcDays(reFromDate, reToDate);
      if (new Date(reToDate) < new Date(reFromDate)) return "End date cannot be before start date.";
      if (days > 30) return "Leave duration cannot exceed 30 days. Please contact your manager.";
    }
    if (!reReason.trim()) return "Please provide a reason for the change.";
    if (reReason.trim().length < 10) return "Reason must be at least 10 characters.";
    return null;
  };

  const submitReapproval = async (e: FormEvent) => {
    e.preventDefault();
    if (!reapprovalTarget) return;
    const validationError = validateReapproval();
    if (validationError) {
      toast({ title: "Validation error", description: validationError, variant: "destructive" });
      return;
    }
    setReSubmitting(true);
    const effectiveToDate = reDateMode === "range" ? reToDate : reFromDate;
    const newDateType = reDateMode === "half" ? "HALF_DAY" : reDateMode.toUpperCase();
    let newDays: number;
    if (reDateMode === "range") newDays = calcDays(reFromDate, effectiveToDate);
    else if (reDateMode === "half") newDays = 0.5;
    else newDays = 1;
    try {
      await api.post<Leave>(`/leaves/${reapprovalTarget.id}/reapproval`, {
        fromDate: reFromDate,
        toDate: effectiveToDate,
        dateType: newDateType,
        halfSession: reDateMode === "half" ? reHalfSession : null,
        leaveType: reapprovalTarget.leaveType,
        days: newDays,
        reason: reReason.trim(),
      });
      toast({
        title: "Change requested",
        description: "Your reapproval request has been sent for the owner's review.",
        className: "border-green-500 bg-green-500 text-white animate-success-bounce",
      });
      setReapprovalTarget(null);
      await load();
    } catch (err) {
      toast({
        title: "Couldn't request change",
        description: getErrorMessage(err) || "An unexpected error occurred.",
        variant: "destructive",
      });
    } finally {
      setReSubmitting(false);
    }
  };

  const cancelReapproval = async (l: Leave) => {
    setCancelingId(l.id);
    try {
      await api.delete(`/leaves/${l.id}/reapproval`);
      toast({ title: "Request withdrawn", description: "Your reapproval request has been cancelled." });
      await load();
    } catch (err) {
      toast({
        title: "Couldn't cancel request",
        description: getErrorMessage(err) || "An unexpected error occurred.",
        variant: "destructive",
      });
    } finally {
      setCancelingId(null);
    }
  };

  // ── Leaves scoped to the selected month ───────────────────────
  const monthFilteredLeaves = leaves.filter((l) => l.fromDate?.slice(0, 7) === historyMonth);

  // ── Counts for tab badges ────────────────────────────────────
  const pendingCount = monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "PENDING").length;
  const allCount = monthFilteredLeaves.length;
  const approvedCount = monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "APPROVED").length;
  const rejectedCount = monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "REJECTED").length;
  const reapprovalCount = monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "REAPPROVAL_PENDING").length;

  // ── Filtered leaves based on selected tab ────────────────────
  const getFilteredLeaves = () => {
    switch (historyTab) {
      case "pending":
        return monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "PENDING");
      case "approved":
        return monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "APPROVED");
      case "rejected":
        return monthFilteredLeaves.filter((l) => l.status?.toUpperCase() === "REJECTED");
      case "all":
      default:
        return monthFilteredLeaves;
    }
  };
  const filteredLeaves = getFilteredLeaves();

  const durationLabel =
    fromDate && toDate ? `${calcDays(fromDate, toDate)} day${calcDays(fromDate, toDate) !== 1 ? "s" : ""}` : null;

  // ── Render ────────────────────────────────────────────────────
  return (
    <div className="space-y-6">
      {/* APPLY FORM */}
      <section className="animate-fade-in-up card-hover overflow-visible rounded-xl border border-border bg-card p-4 shadow-sm sm:p-6">
        <div className="mb-4 flex items-center gap-2">
          <div className="rounded-lg bg-gradient-to-br from-blue-500 to-cyan-600 p-1.5">
            <CalendarCheck2 className="h-4 w-4 text-white" aria-hidden="true" />
          </div>
          <h2 className="text-base font-semibold">Apply for leave</h2>
        </div>

        <form onSubmit={handleSubmit} className="grid gap-4 overflow-visible sm:grid-cols-2" noValidate>
          <div className="space-y-2 overflow-visible">
            <Label htmlFor="leave-type">Leave type</Label>
            <Select value={leaveType} onValueChange={setLeaveType}>
              <SelectTrigger id="leave-type" className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="z-50 overflow-visible">
                <SelectItem value="CASUAL">
                  <LeaveOption title="Casual Leave (CL)" description={`Short personal leave\nFor urgent or unexpected work`} />
                </SelectItem>
                <SelectItem value="SICK">
                  <LeaveOption title="Sick Leave (SL)" description={`Leave when you are ill or injured\nSometimes medical proof is needed`} />
                </SelectItem>
                <SelectItem value="EARNED">
                  <LeaveOption title="Earned Leave / Privilege Leave (EL/PL)" description={`Usually planned in advance`} />
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2 overflow-visible">
            <Label htmlFor="date-type">Date type</Label>
            <Select value={dateMode} onValueChange={(val) => setDateMode(val as "single" | "range" | "half")}>
              <SelectTrigger id="date-type">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="z-50 overflow-visible">
                <SelectItem value="single">Single date</SelectItem>
                <SelectItem value="range">Date range</SelectItem>
                <SelectItem value="half">Half day</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="from">{dateMode === "range" ? "From date" : "Date"}</Label>
            <Input
              id="from"
              type="date"
              required
              min={getMinDate()}
              value={fromDate}
              onChange={(e) => {
                setFromDate(e.target.value);
                if (toDate && e.target.value && new Date(toDate) < new Date(e.target.value)) {
                  setToDate("");
                }
              }}
            />
          </div>

          {dateMode === "range" && (
            <div className="space-y-2">
              <Label htmlFor="to">To date</Label>
              <Input
                id="to"
                type="date"
                required
                min={fromDate || getMinDate()}
                value={toDate}
                onChange={(e) => setToDate(e.target.value)}
                aria-describedby={durationLabel ? "duration-hint" : undefined}
              />
              {durationLabel && (
                <p id="duration-hint" className="text-xs text-muted-foreground">
                  Duration: {durationLabel}
                </p>
              )}
            </div>
          )}

          {dateMode === "half" && (
            <div className="space-y-2">
              <Label htmlFor="half-session">Half day session</Label>
              <Select value={halfSession} onValueChange={(val) => setHalfSession(val as "FIRST_HALF" | "SECOND_HALF")}>
                <SelectTrigger id="half-session">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="FIRST_HALF">First half (morning)</SelectItem>
                  <SelectItem value="SECOND_HALF">Second half (afternoon)</SelectItem>
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">Duration: 0.5 day</p>
            </div>
          )}

          <div className="space-y-2 sm:col-span-2">
            <Label htmlFor="reason">Reason</Label>
            <Textarea
              id="reason"
              required
              rows={3}
              maxLength={500}
              minLength={10}
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              placeholder="Please provide a detailed reason for your leave request..."
              aria-describedby="reason-count"
            />
            <p id="reason-count" className="text-right text-xs text-muted-foreground">
              {reason.length}/500 characters
            </p>
          </div>

          <div className="flex flex-col gap-2 sm:col-span-2 sm:flex-row">
            <Button type="submit" disabled={submitting} className="btn-hover-scale">
              {submitting ? (
                <>
                  <Spinner className="mr-2 text-primary-foreground" />
                  Submitting...
                </>
              ) : (
                "Submit request"
              )}
            </Button>
            <Button type="button" variant="outline" onClick={resetForm} disabled={submitting} className="btn-hover-scale">
              Reset
            </Button>
          </div>
        </form>
      </section>

      {/* LEAVE HISTORY */}
      <section className="animate-slide-right card-hover overflow-hidden rounded-xl border border-border bg-card shadow-sm">
        {/* Header */}
        <div className="flex flex-col gap-3 border-b border-border/60 px-4 py-4 sm:px-6">
          <div>
            <h2 className="text-base font-semibold leading-tight">Leave history</h2>
            <p className="mt-0.5 flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground">
              <span>
                {monthFilteredLeaves.length} request{monthFilteredLeaves.length !== 1 ? "s" : ""} in {format(new Date(`${historyMonth}-01`), "MMMM yyyy")}
              </span>
              {pendingCount > 0 && (
                <span className="inline-flex items-center rounded-full bg-amber-100 px-1.5 py-0.5 text-[11px] font-medium text-amber-700 dark:bg-amber-950/50 dark:text-amber-400">
                  {pendingCount} pending
                </span>
              )}
              {approvedCount > 0 && (
                <span className="inline-flex items-center rounded-full bg-emerald-100 px-1.5 py-0.5 text-[11px] font-medium text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-400">
                  {approvedCount} approved
                </span>
              )}
              {rejectedCount > 0 && (
                <span className="inline-flex items-center rounded-full bg-rose-100 px-1.5 py-0.5 text-[11px] font-medium text-rose-700 dark:bg-rose-950/50 dark:text-rose-400">
                  {rejectedCount} rejected
                </span>
              )}
              {reapprovalCount > 0 && (
                <span className="inline-flex items-center rounded-full bg-amber-100 px-1.5 py-0.5 text-[11px] font-medium text-amber-700 dark:bg-amber-950/50 dark:text-amber-400">
                  {reapprovalCount} reapproval pending
                </span>
              )}
            </p>
          </div>

          {/* Month picker */}
          <div className="w-full max-w-[180px] space-y-1.5">
            <Label htmlFor="employee-history-month" className="text-xs">Month</Label>
            <Input
              id="employee-history-month"
              type="month"
              value={historyMonth}
              onChange={(e) => setHistoryMonth(e.target.value)}
              className="h-9"
            />
          </div>

          {/* Filter tabs */}
          <div role="tablist" aria-label="Filter leave history" className="inline-flex w-full flex-wrap gap-1 rounded-lg border border-border bg-muted/40 p-1">
            <TabButton active={historyTab === "pending"} onClick={() => setHistoryTab("pending")} icon={CalendarClock} label="Pending" count={pendingCount} controls={historyPanelId} />
            <TabButton active={historyTab === "all"} onClick={() => setHistoryTab("all")} icon={CalendarRange} label="All" count={allCount} controls={historyPanelId} />
            <TabButton active={historyTab === "approved"} onClick={() => setHistoryTab("approved")} icon={CalendarCheck2} label="Approved" count={approvedCount} controls={historyPanelId} />
            <TabButton active={historyTab === "rejected"} onClick={() => setHistoryTab("rejected")} icon={CalendarX2} label="Rejected" count={rejectedCount} controls={historyPanelId} />
          </div>
        </div>

        {/* Body */}
        <div id={historyPanelId} role="tabpanel" className="p-4 sm:p-6">
          {loading ? (
            <div className="flex justify-center py-8">
              <FullSpinner />
            </div>
          ) : error ? (
            <ErrorState message={error} onRetry={load} />
          ) : filteredLeaves.length === 0 ? (
            <EmptyState
              message={
                historyTab === "pending"
                  ? `No pending leave requests in ${format(new Date(`${historyMonth}-01`), "MMMM yyyy")}.`
                  : historyTab === "all"
                  ? `No leave requests in ${format(new Date(`${historyMonth}-01`), "MMMM yyyy")}.`
                  : historyTab === "approved"
                  ? `No approved leaves in ${format(new Date(`${historyMonth}-01`), "MMMM yyyy")}.`
                  : `No rejected leaves in ${format(new Date(`${historyMonth}-01`), "MMMM yyyy")}.`
              }
            />
          ) : (
            <AppliedLeavesTable
              leaves={filteredLeaves}
              onRequestChange={openReapproval}
              onCancelReapproval={cancelReapproval}
              cancelingId={cancelingId}
            />
          )}
        </div>
      </section>

      {/* Reapproval Modal */}
      {reapprovalTarget && (
        <div
          className="animate-fade-slide-down fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"
          onClick={closeReapproval}
          role="presentation"
        >
          <div
            role="dialog"
            aria-modal="true"
            aria-labelledby="reapproval-title"
            className="custom-scrollbar max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-border bg-card p-5 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-4 flex items-center justify-between gap-3">
              <div>
                <h3 id="reapproval-title" className="text-base font-semibold">
                  Request a change
                </h3>
                <p className="mt-0.5 text-xs text-muted-foreground">
                  Propose new details for your approved leave. It'll go back to your manager for reapproval.
                </p>
              </div>
              <button
                ref={modalCloseButtonRef}
                type="button"
                onClick={closeReapproval}
                className={`rounded-full p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground ${FOCUS_RING}`}
                aria-label="Close dialog"
              >
                ✕
              </button>
            </div>

            <div className="mb-4 rounded-lg border border-border bg-muted/30 p-3 text-xs text-muted-foreground">
              Currently approved:{" "}
              <span className="font-medium text-foreground">
                {reapprovalTarget.fromDate === reapprovalTarget.toDate
                  ? fmt(reapprovalTarget.fromDate)
                  : `${fmt(reapprovalTarget.fromDate)} → ${fmt(reapprovalTarget.toDate)}`}
              </span>{" "}
              · {formatDateType(reapprovalTarget.dateType, reapprovalTarget.halfSession)}
            </div>

            <form onSubmit={submitReapproval} className="grid gap-4 sm:grid-cols-2" noValidate>
              <div className="space-y-2">
                <Label htmlFor="re-date-type">Date type</Label>
                <Select value={reDateMode} onValueChange={(val) => setReDateMode(val as "single" | "range" | "half")}>
                  <SelectTrigger id="re-date-type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="single">Single date</SelectItem>
                    <SelectItem value="range">Date range</SelectItem>
                    <SelectItem value="half">Half day</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="re-from">{reDateMode === "range" ? "New from date" : "New date"}</Label>
                <Input
                  id="re-from"
                  type="date"
                  required
                  value={reFromDate}
                  onChange={(e) => {
                    setReFromDate(e.target.value);
                    if (reToDate && e.target.value && new Date(reToDate) < new Date(e.target.value)) {
                      setReToDate("");
                    }
                  }}
                />
              </div>

              {reDateMode === "range" && (
                <div className="space-y-2">
                  <Label htmlFor="re-to">New to date</Label>
                  <Input id="re-to" type="date" required min={reFromDate} value={reToDate} onChange={(e) => setReToDate(e.target.value)} />
                  {reFromDate && reToDate && (
                    <p className="text-xs text-muted-foreground">
                      Duration: {calcDays(reFromDate, reToDate)} day{calcDays(reFromDate, reToDate) !== 1 ? "s" : ""}
                    </p>
                  )}
                </div>
              )}

              {reDateMode === "half" && (
                <div className="space-y-2">
                  <Label htmlFor="re-half-session">Half day session</Label>
                  <Select value={reHalfSession} onValueChange={(val) => setReHalfSession(val as "FIRST_HALF" | "SECOND_HALF")}>
                    <SelectTrigger id="re-half-session">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="FIRST_HALF">First half (morning)</SelectItem>
                      <SelectItem value="SECOND_HALF">Second half (afternoon)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              )}

              <div className="space-y-2 sm:col-span-2">
                <Label htmlFor="re-reason">Reason for the change</Label>
                <Textarea
                  id="re-reason"
                  required
                  rows={3}
                  maxLength={500}
                  minLength={10}
                  value={reReason}
                  onChange={(e) => setReReason(e.target.value)}
                  placeholder="Explain why you need to change your approved leave..."
                  aria-describedby="re-reason-count"
                />
                <p id="re-reason-count" className="text-right text-xs text-muted-foreground">
                  {reReason.length}/500 characters
                </p>
              </div>

              <div className="flex flex-col gap-2 sm:col-span-2 sm:flex-row">
                <Button type="submit" disabled={reSubmitting} className="btn-hover-scale">
                  {reSubmitting ? (
                    <>
                      <Spinner className="mr-2 text-primary-foreground" />
                      Submitting...
                    </>
                  ) : (
                    "Submit for reapproval"
                  )}
                </Button>
                <Button type="button" variant="outline" onClick={closeReapproval} disabled={reSubmitting} className="btn-hover-scale">
                  Cancel
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

/* =========================================================
   OWNER VIEW
========================================================= */

const OwnerView = () => {
  const [ownerTab, setOwnerTab] = useState<"pending" | "summary" | "employee">("pending");
  const ownerPanelId = useId();
  const [leaves, setLeaves] = useState<Leave[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [actingId, setActingId] = useState<string | number | null>(null);

  const [employeeNames, setEmployeeNames] = useState<string[]>([]);
  const [namesLoading, setNamesLoading] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<string>("");
  const [empLeaves, setEmpLeaves] = useState<Leave[]>([]);
  const [empLoading, setEmpLoading] = useState(false);
  const [empError, setEmpError] = useState<string | null>(null);
  // Pending / All / Approved / Rejected sub-filter within the selected
  // employee's history — mirrors the employee's own history tabs, but
  // scoped to the one employee the owner picked.
  const [empHistoryTab, setEmpHistoryTab] = useState<"pending" | "all" | "approved" | "rejected">("all");
  // Selected employee's annual leave limit (24 vs 18 days, based on date
  // of joining), fetched alongside their leave history.
  const [empLeaveLimit, setEmpLeaveLimit] = useState<number>(DEFAULT_LEAVE_LIMIT);

  // ── Month filter for the Employee History tab ──────────────────────────
  // "yyyy-MM", defaults to the current month. Powers /leaves/employee-monthly
  // so an owner can see how many leaves were approved/rejected/pending for
  // this employee in a specific month.
  const [empMonth, setEmpMonth] = useState<string>(() => format(new Date(), "yyyy-MM"));
  const [empMonthCounts, setEmpMonthCounts] = useState<{
    approved: number;
    rejected: number;
    pending: number;
    approvedDays: number;
  } | null>(null);
  const [empMonthLoading, setEmpMonthLoading] = useState(false);

  // ── All-employees summary tab ─────────────────────────────────────────
  const [summaries, setSummaries] = useState<EmployeeLeaveSummary[]>([]);
  const [summaryLoading, setSummaryLoading] = useState(false);
  const [summaryError, setSummaryError] = useState<string | null>(null);

  const initialLoadDoneRef = useRef(false);
  const loadingLockRef = useRef(false);
  const empLoadingLockRef = useRef(false);
  const namesLoadedRef = useRef(false);
  const summaryLoadingLockRef = useRef(false);

  const load = useCallback(async () => {
    if (loadingLockRef.current) return;
    loadingLockRef.current = true;
    setLoading(true);
    setError(null);
    try {
      const { data } = await api.get<Leave[]>("/leaves/pending");
      setLeaves(data);
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setLoading(false);
      loadingLockRef.current = false;
    }
  }, []);

  useEffect(() => {
    if (!initialLoadDoneRef.current) {
      initialLoadDoneRef.current = true;
      load();
    }
  }, [load]);

  const loadEmployeeNames = useCallback(async () => {
    if (namesLoadedRef.current) return;
    if (empLoadingLockRef.current) return;
    empLoadingLockRef.current = true;
    setNamesLoading(true);
    try {
      const { data } = await api.get<string[]>("/employees/name", { params: { roles: ["USER", "LEAD"] } });
      setEmployeeNames(data);
      namesLoadedRef.current = true;
    } catch {
      setEmployeeNames([]);
      toast({ title: "Couldn't load employees", description: "The employee list failed to load.", variant: "destructive" });
    } finally {
      setNamesLoading(false);
      empLoadingLockRef.current = false;
    }
  }, []);

  useEffect(() => {
    if ((ownerTab === "employee" || ownerTab === "summary") && !namesLoadedRef.current) {
      loadEmployeeNames();
    }
  }, [ownerTab, loadEmployeeNames]);

  const loadSummaries = useCallback(async () => {
    if (summaryLoadingLockRef.current) return;
    summaryLoadingLockRef.current = true;
    setSummaryLoading(true);
    setSummaryError(null);
    try {
      const { data } = await api.get<EmployeeLeaveSummary[]>("/leaves/summary", {
        headers: { "Cache-Control": "no-cache" },
      });
      setSummaries(data);
    } catch (err) {
      setSummaryError(getErrorMessage(err));
    } finally {
      setSummaryLoading(false);
      summaryLoadingLockRef.current = false;
    }
  }, []);

  useEffect(() => {
    if (ownerTab === "summary") {
      loadSummaries();
    }
  }, [ownerTab, loadSummaries]);

  // Jumping from the "All employees" summary straight to an employee's full history.
  const viewEmployeeFromSummary = (empName: string) => {
    setOwnerTab("employee");
    loadEmployeeNames();
    handleEmployeeSelect(empName);
  };

  const loadEmpLeaves = useCallback(async (empName: string) => {
    if (!empName) return;
    if (empLoadingLockRef.current) return;
    empLoadingLockRef.current = true;
    setEmpLoading(true);
    setEmpError(null);
    setEmpLeaves([]);
    try {
      const [{ data }, limitRes] = await Promise.all([
        api.get<Leave[]>("/leaves/employee", { params: { employeeName: empName } }),
        api.get<{ leaveLimit: number }>("/leaves/leave-limit", { params: { employeeName: empName } }).catch(() => null), // non-fatal — fall back to the default limit
      ]);
      setEmpLeaves(data);
      setEmpLeaveLimit(limitRes ? limitRes.data.leaveLimit : DEFAULT_LEAVE_LIMIT);
    } catch (err) {
      setEmpError(getErrorMessage(err));
    } finally {
      setEmpLoading(false);
      empLoadingLockRef.current = false;
    }
  }, []);

  const handleEmployeeSelect = (name: string) => {
    setSelectedEmployee(name);
    setEmpHistoryTab("all");
    loadEmpLeaves(name);
  };

  // Keep the selected employee's leave limit/history fresh if their
  // Date of Joining is edited while this tab is sitting in the background.
  useEffect(() => {
    if (!selectedEmployee) return;
    const refetch = () => loadEmpLeaves(selectedEmployee);
    const onVisibility = () => {
      if (document.visibilityState === "visible") refetch();
    };
    window.addEventListener("focus", refetch);
    document.addEventListener("visibilitychange", onVisibility);
    return () => {
      window.removeEventListener("focus", refetch);
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, [selectedEmployee, loadEmpLeaves]);

  // ── Month-filtered approved/rejected/pending counts for the selected employee ──
  const loadEmpMonthCounts = useCallback(async (empName: string, month: string) => {
    if (!empName || !month) return;
    setEmpMonthLoading(true);
    try {
      const { data } = await api.get<{
        counts: { approved: number; rejected: number; pending: number; approvedDays: number };
      }>("/leaves/employee-monthly", { params: { employeeName: empName, month } });
      setEmpMonthCounts(data.counts);
    } catch {
      setEmpMonthCounts(null);
    } finally {
      setEmpMonthLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!selectedEmployee) return;
    loadEmpMonthCounts(selectedEmployee, empMonth);
  }, [selectedEmployee, empMonth, loadEmpMonthCounts]);

  const act = async (id: string | number, action: "APPROVED" | "REJECTED") => {
    setActingId(id);
    try {
      await api.put(`/leaves/${id}/${action}`);
      toast({
        title: action === "APPROVED" ? "Leave approved" : "Leave rejected",
        description:
          action === "APPROVED" ? "The leave request has been approved successfully." : "The leave request has been rejected.",
        className:
          action === "APPROVED" ? "border-green-500 bg-green-500 text-white animate-success-bounce" : "border-red-500 bg-red-500 text-white",
      });
      await load();
      if (selectedEmployee) await loadEmpLeaves(selectedEmployee);
    } catch (err) {
      toast({ title: "Action failed", description: getErrorMessage(err) || "An unexpected error occurred.", variant: "destructive" });
    } finally {
      setActingId(null);
    }
  };

  const currentYear = new Date().getFullYear();
  const empTakenDays = empLeaves
    .filter((l) => l.status?.toUpperCase() === "APPROVED" && new Date(l.fromDate).getFullYear() === currentYear)
    .reduce((sum, l) => sum + (l.days || 0), 0);
  const empIsOver = empTakenDays > empLeaveLimit;
  const empRemaining = empLeaveLimit - empTakenDays;

  const sortedEmpLeaves = [...empLeaves]
    .filter((l) => l.fromDate?.slice(0, 7) === empMonth)
    .sort((a, b) => {
      try {
        return new Date(b.fromDate).getTime() - new Date(a.fromDate).getTime();
      } catch {
        return 0;
      }
    });

  // ── Pending / All / Approved / Rejected counts + filter, scoped to the
  // selected employee's month-filtered records ──
  const empPendingCount = sortedEmpLeaves.filter((l) => l.status?.toUpperCase() === "PENDING" || l.status?.toUpperCase() === "REAPPROVAL_PENDING").length;
  const empApprovedTabCount = sortedEmpLeaves.filter((l) => l.status?.toUpperCase() === "APPROVED").length;
  const empRejectedTabCount = sortedEmpLeaves.filter((l) => l.status?.toUpperCase() === "REJECTED").length;
  const filteredEmpLeaves = sortedEmpLeaves.filter((l) => {
    const status = l.status?.toUpperCase();
    if (empHistoryTab === "pending") return status === "PENDING" || status === "REAPPROVAL_PENDING";
    if (empHistoryTab === "approved") return status === "APPROVED";
    if (empHistoryTab === "rejected") return status === "REJECTED";
    return true;
  });

  return (
    <section className="animate-fade-in-up card-hover overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      {/* Header */}
      <div className="flex flex-col gap-3 border-b border-border/60 px-4 py-4 sm:px-6">
        <div>
          <h2 className="text-base font-semibold leading-tight">Leave management</h2>
          <p className="mt-0.5 text-xs text-muted-foreground">
            {ownerTab === "pending"
              ? `${leaves.length} pending request${leaves.length !== 1 ? "s" : ""}`
              : ownerTab === "summary"
              ? "Leave days used and remaining for every employee this year"
              : selectedEmployee
              ? `Showing history for ${selectedEmployee}`
              : "Select an employee to view their leave history"}
          </p>
        </div>

        {/* Tab toggle */}
        <div role="tablist" aria-label="Leave management sections" className="inline-flex w-full items-center rounded-lg border border-border bg-muted/40 p-1 sm:w-auto">
          <TabButton active={ownerTab === "pending"} onClick={() => setOwnerTab("pending")} icon={CalendarClock} label="Pending" count={leaves.length} controls={ownerPanelId} />
          <TabButton active={ownerTab === "summary"} onClick={() => setOwnerTab("summary")} icon={Users} label="All employees" controls={ownerPanelId} />
          <TabButton active={ownerTab === "employee"} onClick={() => setOwnerTab("employee")} icon={Users} label="Employee history" controls={ownerPanelId} />
        </div>
      </div>

      <div id={ownerPanelId} role="tabpanel" className="p-4 sm:p-6">
        {/* ══ PENDING TAB ══ */}
        {ownerTab === "pending" && (
          <>
            {loading ? (
              <div className="flex justify-center py-8">
                <FullSpinner />
              </div>
            ) : error ? (
              <ErrorState message={error} onRetry={load} />
            ) : leaves.length === 0 ? (
              <EmptyState icon={CalendarCheck2} message="No pending leave requests." />
            ) : (
              <div className="space-y-3">
                {leaves.map((l, index) => (
                  <LeaveCard key={l.id} leave={l} index={index} showEmployee onApprove={(leave) => act(leave.id, "APPROVED")} onReject={(leave) => act(leave.id, "REJECTED")} actingId={actingId} />
                ))}
              </div>
            )}
          </>
        )}

        {/* ══ ALL EMPLOYEES SUMMARY TAB ══ */}
        {ownerTab === "summary" && (
          <>
            {summaryLoading ? (
              <div className="flex justify-center py-8">
                <FullSpinner />
              </div>
            ) : summaryError ? (
              <ErrorState message={summaryError} onRetry={loadSummaries} />
            ) : summaries.length === 0 ? (
              <EmptyState icon={Users} message="No employees found." />
            ) : (
              <EmployeeSummaryTable summaries={summaries} onView={viewEmployeeFromSummary} />
            )}
          </>
        )}

        {/* ══ EMPLOYEE HISTORY TAB ══ */}
        {ownerTab === "employee" && (
          <div className="animate-fade-in-up space-y-5">
            <div className="flex flex-col gap-4 sm:flex-row">
              <div className="w-full max-w-xs space-y-2">
                <Label htmlFor="owner-employee-select">Select employee</Label>
                <Select value={selectedEmployee} onValueChange={handleEmployeeSelect} disabled={namesLoading}>
                  <SelectTrigger id="owner-employee-select">
                    <SelectValue placeholder={namesLoading ? "Loading..." : "Choose an employee"} />
                  </SelectTrigger>
                  <SelectContent>
                    {employeeNames.map((n) => (
                      <SelectItem key={n} value={n}>
                        {n}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="w-full max-w-[180px] space-y-2">
                <Label htmlFor="owner-month-select">Month</Label>
                <Input id="owner-month-select" type="month" value={empMonth} onChange={(e) => setEmpMonth(e.target.value)} className="h-9" />
              </div>
            </div>

            {!selectedEmployee ? (
              <EmptyState icon={CalendarCheck2} message="Select an employee above to view their leave history." />
            ) : empLoading ? (
              <div className="flex justify-center py-8">
                <FullSpinner />
              </div>
            ) : empError ? (
              <ErrorState message={empError} onRetry={() => loadEmpLeaves(selectedEmployee)} />
            ) : empLeaves.length === 0 ? (
              <EmptyState message={`No leave records found for ${selectedEmployee}.`} />
            ) : (
              <div className="space-y-4">
                {/* Summary banner */}
                <div
                  role="status"
                  className={`rounded-lg border px-4 py-3 ${
                    empIsOver
                      ? "border-red-300 bg-red-50 dark:border-red-900/50 dark:bg-red-950/30"
                      : "border-green-300 bg-green-50 dark:border-green-900/50 dark:bg-green-950/30"
                  }`}
                  style={{
                    animation: empIsOver
                      ? "empWarnPulse 1.8s ease-in-out infinite, empSlideIn 0.35s ease"
                      : "empGoodPulse 2.5s ease-in-out infinite, empSlideIn 0.35s ease",
                  }}
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="flex min-w-0 items-start gap-3">
                      <span className="relative mt-0.5 flex h-3 w-3 flex-shrink-0" aria-hidden="true">
                        <span className={`absolute inline-flex h-full w-full animate-ping rounded-full opacity-75 ${empIsOver ? "bg-red-400" : "bg-green-400"}`} />
                        <span className={`relative inline-flex h-3 w-3 rounded-full ${empIsOver ? "bg-red-500" : "bg-green-500"}`} />
                      </span>
                      <div className="min-w-0">
                        <p
                          className={`text-sm font-bold ${empIsOver ? "text-red-600 dark:text-red-400" : "text-green-700 dark:text-green-400"}`}
                          style={empIsOver ? { animation: "empShake 0.5s ease-in-out 0.4s 1" } : {}}
                        >
                          {empIsOver ? (
                            <>
                              <span aria-hidden="true">⚠</span> {selectedEmployee} has exceeded the leave limit
                            </>
                          ) : (
                            <>
                              <span aria-hidden="true">✓</span> {selectedEmployee} is within the leave limit
                            </>
                          )}
                        </p>
                        <p className={`mt-0.5 text-xs ${empIsOver ? "text-red-500 dark:text-red-400/80" : "text-green-600 dark:text-green-400/80"}`}>
                          {empIsOver
                            ? `${empTakenDays} / ${empLeaveLimit} days — ${Math.abs(empRemaining)} day${Math.abs(empRemaining) !== 1 ? "s" : ""} over limit`
                            : `${empTakenDays} / ${empLeaveLimit} days — ${empRemaining} day${empRemaining !== 1 ? "s" : ""} remaining`}
                        </p>
                      </div>
                    </div>

                    {/* Progress bar */}
                    <div className="flex w-full flex-col items-end gap-1 sm:w-auto">
                      <span className={`text-xs font-semibold ${empIsOver ? "text-red-600 dark:text-red-400" : "text-green-700 dark:text-green-400"}`}>
                        {empTakenDays} / {empLeaveLimit} days
                      </span>
                      <div className="h-2 w-full overflow-hidden rounded-full border border-white/40 bg-white/60 dark:border-white/10 dark:bg-white/10 sm:w-28">
                        <div
                          className={`h-full rounded-full transition-all duration-700 ${empIsOver ? "bg-red-500" : "bg-green-500"}`}
                          style={{ width: `${Math.min((empTakenDays / empLeaveLimit) * 100, 100)}%` }}
                        />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Approved / Rejected / Pending counts for the selected month */}
                <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                  <div className="rounded-lg border border-border bg-muted/30 px-3 py-2">
                    <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Approved Request</p>
                    <p className="text-lg font-bold text-green-600 dark:text-green-400">{empMonthLoading ? "…" : empMonthCounts?.approved ?? 0}</p>
                  </div>
                  <div className="rounded-lg border border-border bg-muted/30 px-3 py-2">
                    <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Rejected Request</p>
                    <p className="text-lg font-bold text-red-600 dark:text-red-400">{empMonthLoading ? "…" : empMonthCounts?.rejected ?? 0}</p>
                  </div>
                  <div className="rounded-lg border border-border bg-muted/30 px-3 py-2">
                    <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Pending Request</p>
                    <p className="text-lg font-bold text-amber-600 dark:text-amber-400">{empMonthLoading ? "…" : empMonthCounts?.pending ?? 0}</p>
                  </div>
                  <div className="rounded-lg border border-border bg-muted/30 px-3 py-2">
                    <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Approved days</p>
                    <p className="text-lg font-bold text-foreground">{empMonthLoading ? "…" : empMonthCounts?.approvedDays ?? 0}</p>
                  </div>
                </div>

                {/* Pending / All / Approved / Rejected sub-filter for this employee */}
                <div role="tablist" aria-label="Filter this employee's leave records" className="inline-flex w-full flex-wrap gap-1 rounded-lg border border-border bg-muted/40 p-1">
                  <TabButton active={empHistoryTab === "pending"} onClick={() => setEmpHistoryTab("pending")} icon={CalendarClock} label="Pending" count={empPendingCount} controls={ownerPanelId} />
                  <TabButton active={empHistoryTab === "all"} onClick={() => setEmpHistoryTab("all")} icon={CalendarRange} label="All" count={sortedEmpLeaves.length} controls={ownerPanelId} />
                  <TabButton active={empHistoryTab === "approved"} onClick={() => setEmpHistoryTab("approved")} icon={CalendarCheck2} label="Approved" count={empApprovedTabCount} controls={ownerPanelId} />
                  <TabButton active={empHistoryTab === "rejected"} onClick={() => setEmpHistoryTab("rejected")} icon={CalendarX2} label="Rejected" count={empRejectedTabCount} controls={ownerPanelId} />
                </div>

                {/* Employee leave cards, filtered by the sub-tab above */}
                {filteredEmpLeaves.length === 0 ? (
                  <EmptyState message={`No ${empHistoryTab === "all" ? "" : empHistoryTab + " "}leave records found for ${selectedEmployee} in ${empMonth}.`} />
                ) : (
                  <div className="space-y-3">
                    {filteredEmpLeaves.map((l, index) => (
                      <LeaveCard
                        key={l.id}
                        leave={l}
                        index={index}
                        onApprove={(leave) => act(leave.id, "APPROVED")}
                        onReject={(leave) => act(leave.id, "REJECTED")}
                        actingId={actingId}
                      />
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  );
};

/* =========================================================
   MAIN PAGE
========================================================= */

const LeavePortal = () => {
  const { role } = useAuth();
  return (
    <>
      <PageHeader
        title="Leave Portal"
        description={role === "OWNER" ? "Review and act on employee leave requests." : "Apply for leave and track your requests."}
      />
      {role === "OWNER" ? <OwnerView /> : <EmployeeView />}
    </>
  );
};

export default LeavePortal;